Отрисуй меня полностью (часть 2) — для сложных проектов
htmlacademy-javascript/2002115-kekstagram-27 pull request #6
Opened 2022-11-15 10:55 UTC by Anechua

2022-11-16 07:07 UTC, 4err requested changes

2022-11-16 07:07 UTC, 4err commented on js/photos.js
> +      const currentPhoto = photos[previews.indexOf(preview)];
Неплохая мысль, однако, как только произойдет фильтрация или изменится порядок изображений все сломается. 
Тут нужно использовать подход с замыканием, это и упростит решение задачи и предотвратит ошибки связанные с реорганизацией порядка массива. 
Ты можешь вешать обработчик клика на карточку в момент ее созданий, таким образом ты с помощью замыкания свяжешь данные карточки в событии и саму карточку и тебе не нужно будет заниматься определением, по какому элементу ткнул пользователь.

2022-11-16 07:07 UTC, 4err commented on js/photos.js
> +const getSocialCommentsList = (comments) => {
`get` это все-таки когда ты что-то получаешь откуда-то. Тут же отрисовка комментариев, вероятно это должен быть `render`

2022-11-18 15:51 UTC, Anechua commented on js/photos.js
> +      const currentPhoto = photos[previews.indexOf(preview)];
Не уверена, что в итоге у меня получилось то, как ты предложил, но по крайней мере проблема определяния элемента, по которому ткнул пользователь, решена. Во всяком случае я не вижу, где у меня получилось замыкание. (никак не укладывается принцип этого метода в голове).

2022-11-18 15:53 UTC, Anechua commented
Я случайно накосячила с коммитами, не увидела, что закоммитилась в мастер. Поэтому пришлось исправлять ситуацию.

2022-11-19 06:08 UTC, merged