Правда или действие
htmlacademy-javascript/2002115-kekstagram-27 pull request #7
Opened 2022-11-20 15:44 UTC by Anechua

2022-11-20 21:56 UTC, Anechua commented
В связи с тем, что время поджимает, выполнила обе части 8 домашки сразу

2022-11-21 07:15 UTC, 4err requested changes

2022-11-21 07:15 UTC, 4err commented on js/photo-modal.js
> +const getHiddenComments = () => photoModal.querySelectorAll('.social__comment.hidden');
Не, такое решение не подходит. Мы и загружаем данные по частям, чтоб не загружать страницу пользователя и сервер. Представь, что там тысяча комментариев? 10 тысяч? А нам нужно показать только 5, но рисовать мы будем все и скрывать их. 
Нужно реализовать именно добавление на страницу новой партии комментариев.

2022-11-21 07:15 UTC, 4err commented on js/util.js
> +const toggleNumberRange = (options, operation) => {
Здесь удобно использовать деструктуризацию объекта `options`, т.к. всего 4 коротких ключа, однако, тебе не придется каждый раз писать `options` и код будет проще для восприятия. 
`{value, step, min, max}`

2022-11-21 07:15 UTC, 4err commented on js/util.js
> +const checkRepeats = (array) => {
Можно упростить себе жизнь, используя метод `includes`. Или еще больше упростить, используя структуру `Set`. 
https://learn.javascript.ru/map-set#set

Set хранит только уникальные значения, поэтому превратив массив в сет и посчитав его длину, мы можем сравнить ее с исходной. Если она отличается, значит были дубликаты :)

2022-11-21 07:15 UTC, 4err commented on js/validation.js
> +const HASHTAG_RULES = '- должен начинаться с символа # (решётка);<br>- может состоять из букв и чисел;<br>- не может содержать пробелы, спецсимволы (#, @, $ и т. п.), символы пунктуации (тире, дефис,
Очень страшные правила и для пользователя абсолютно не понятно, что именно он делает не так. 
Нужно для каждого правила написать свою проверку и выводить именно то сообщение, которое нарушается в текущем написании хэштегов.

2022-11-22 05:50 UTC, Anechua commented
Решила отправить сразу слайдер на проверку. Делаю всё подряд :)

2022-11-22 07:13 UTC, 4err requested changes
https://take.ms/ReIHW Он заставляет меня ввести хештег, хотя он не является обязательным. 

Для слайдера для эффекта "Оригинал" нужно убирать серую подложку слайдера.

2022-11-22 07:13 UTC, 4err commented on js/effects.js
> +const cleanEffect = () => {
Лучше `clear`

2022-11-22 07:13 UTC, 4err commented on js/form-modal.js
> +  // eslint-disable-next-line no-use-before-define
Запреты линтера использовать нельзя. Для таких ситуаций можно использовать объявление функций через `function ()`

2022-11-22 07:13 UTC, 4err commented on js/photo-modal.js
> +  const currentAmount = photoModal.querySelectorAll(tagName).length;
Лучше просто использовать переменную-счетчик, в которой будет храниться текущее количество отображаемых комментов, это сделать несложно, ты же сама добавляешь их по нажатию на кнопку. А вот каждый раз делать `querySelectorAll` такое себе. Это достаточно ресурсозатратная операция, лучше стараться избегать ее бессмысленное вызывание.

2022-11-22 07:13 UTC, 4err commented on js/util.js
> +};
options можно было развернуть прям в аргументах функции. 
Вот то, что ты делаешь в этой функции, это называется неявное изменение объекта. Это очень плохо :) Обрати, внимание, что хоть ты и пишешь тут `return` в вызове функции, ты результат ничему не присваиваешь. 
Т.к. это объект, он передается в функцию по ссылке и когда ты меняешь его внутри функции, он меняется везде. Так делать не стоит, это приведет к множеству сложно уловимых ошибок в будущем. 
Если нужно изменять объект, то нужно делать обязательно копию и работать с ней, с массивом аналогично. 
В нашем случае тебе вообще не нужен объект целиком. Тебе нужно только итоговое значение поля `value`, так почему-бы его и не возвращать? Это не приведет к изменению объекта, а дальше, с помощью `value` ты можешь установить нужный масштаб.

2022-11-22 07:13 UTC, 4err commented on js/scale.js
> +const getScaleValue = (photo, options) => {
`set` же. Ты устанавливаешь новое значение, а не получаешь текущее.

2022-11-23 18:20 UTC, merged